//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStudents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelStudentsContainer : DbContext
    {
        public ModelStudentsContainer()
            : base("name=ModelStudentsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Студент> СтудентSet { get; set; }
        public virtual DbSet<Предмет> ПредметSet { get; set; }
        public virtual DbSet<ПредмСтуд> ПредмСтудSet { get; set; }
    }
}
